name: mobiliz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  auto_route: ^10.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  flutter_svg: ^2.0.17
  iconsax_plus: ^1.0.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  provider: ^6.1.2
dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
flutter:
  uses-material-design: true
  assets:
    - path: assets/icons/
